# -*- coding: utf-8 -*-
"""Smart_Water_Distribution_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ykQ654iVxAQhsfuLRz6Ski7fFfC_AbD

# Smart Water Distribution Analytics System
## CDAC Mumbai - AI Compute Platform
Complete PySpark Solution (Q1–Q7)
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import LinearRegression
from pyspark.ml.evaluation import RegressionEvaluator

spark = SparkSession.builder.appName("Smart Water Distribution Analytics").getOrCreate()
sc = spark.sparkContext
print(sc)

"""## Q1 - Load Dataset"""

df = spark.read.csv(
    "/content/DataSetAICompuetRelab.csv",
    header=True,
    inferSchema=True
)

df.printSchema()
df.show(10)
print("Total Records:", df.count())
df.describe().show()

"""## Q2 - RDD Programming"""

rdd = df.rdd

zone_rdd = rdd.map(lambda x: x.Zone)
high_loss = rdd.filter(lambda x: x.Water_Loss_Liters > 10000)
flat = rdd.flatMap(lambda x: x.Zone.split())

print("RDD Count:", rdd.count())
print(zone_rdd.collect()[:10])

total_supply = rdd.map(lambda x: x.Supply_Volume_Liters).reduce(lambda a,b:a+b)
print("Total Supply:", total_supply)

zone_supply = rdd.map(lambda x:(x.Zone,x.Supply_Volume_Liters)).reduceByKey(lambda a,b:a+b)
print(zone_supply.collect())

"""## Q3 - DataFrame Operations"""

df.select(
    "Zone",
    "Distribution_Station",
    "Supply_Volume_Liters",
    "Consumption_Liters"
).show()

df.filter(
    (col("Water_Loss_Liters")>1000) &
    (col("Leakage_Events")>2)
).show()

df.orderBy(col("Water_Loss_Liters").desc()).show()

df.groupBy("Zone").count().show()

df.groupBy("Zone").agg(
    sum("Supply_Volume_Liters").alias("Total Supply"),
    sum("Consumption_Liters").alias("Total Consumption"),
    sum("Water_Loss_Liters").alias("Total Loss"),
    avg("Pressure_PSI").alias("Average Pressure"),
    avg("Maintenance_Cost").alias("Average Cost")
).show()

"""## Q4 - Spark SQL"""

df.createOrReplaceTempView("water")

spark.sql("""
SELECT Zone,SUM(Consumption_Liters) AS TotalConsumption
FROM water
GROUP BY Zone
ORDER BY TotalConsumption DESC
LIMIT 5
""").show()

spark.sql("""
SELECT Zone,
SUM(Water_Loss_Liters) TotalLoss,
AVG(Water_Loss_Liters) AvgLoss,
MAX(Water_Loss_Liters) MaxLoss
FROM water
GROUP BY Zone
""").show()

spark.sql("""
SELECT Distribution_Station,
ROUND(SUM(Consumption_Liters)/SUM(Supply_Volume_Liters)*100,2) AS Efficiency
FROM water
GROUP BY Distribution_Station
ORDER BY Efficiency DESC
""").show()

spark.sql("""
SELECT month(Supply_Date) Month,
SUM(Supply_Volume_Liters) Supply
FROM water
GROUP BY month(Supply_Date)
ORDER BY Month
""").show()

spark.sql("""
SELECT month(Supply_Date) Month,
SUM(Consumption_Liters) Consumption
FROM water
GROUP BY month(Supply_Date)
ORDER BY Month
""").show()

spark.sql("""
SELECT Zone,
SUM(Leakage_Events) Leakages
FROM water
GROUP BY Zone
ORDER BY Leakages DESC
""").show()

spark.sql("""
SELECT Water_Source,
AVG(PH_Value) AvgPH,
AVG(Turbidity_NTU) AvgTurbidity
FROM water
GROUP BY Water_Source
""").show()

"""## Q5 - ETL Pipeline"""

etl = spark.read.csv(
    "/content/DataSetAICompuetRelab.csv",
    header=True,
    inferSchema=True
)

etl = etl.dropDuplicates()
etl = etl.na.fill(0)
etl = etl.withColumn("Supply_Date", to_date("Supply_Date"))

etl.write.mode("overwrite").parquet("Water_Data_Parquet")

print("ETL Completed")

"""### ETL Workflow

CSV → Extract → Remove Duplicates → Handle Missing Values → Convert Data Types → Save as Parquet

## Q6 - Spark MLlib
"""

assembler = VectorAssembler(
    inputCols=[
        "Supply_Volume_Liters",
        "Pressure_PSI",
        "Consumer_Count",
        "Leakage_Events"
    ],
    outputCol="features"
)

data = assembler.transform(df)

train,test = data.randomSplit([0.8,0.2],seed=1)

lr = LinearRegression(
    featuresCol="features",
    labelCol="Consumption_Liters"
)

model = lr.fit(train)

prediction = model.transform(test)
prediction.select("Consumption_Liters","prediction").show()

evaluator = RegressionEvaluator(
    labelCol="Consumption_Liters",
    predictionCol="prediction",
    metricName="rmse"
)

print("RMSE:", evaluator.evaluate(prediction))

"""## Q7 - GitHub and CI/CD"""

# Git Commands

# git init
# git add .
# git commit -m "Smart Water Analytics"
# git branch -M main
# git remote add origin https://github.com/username/Smart-Water-Analytics.git
# git push -u origin main

"""### GitHub Actions (spark.yml)

```yaml
name: Spark CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pyspark pandas
      - run: python main.py
```

"""